# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiI5ZmMzODUxYy1lNDMwLTQwZjQtODQxNi0xNDJkODhlZTYzZWYiLCJpYXQiOjE3Mzc1MzYzODEsImV4cCI6MTc0MDEyODM4MX0.h5qVjYKF_76SPRFhRULzOQ6E2_KXgkZd7AWVLWnQeH8

###

# Create a new post
POST http://localhost:3000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzU0NzE1MSwiZXhwIjoxNzM3NTQ3NDUxfQ.4b08bkGttfN_rAv_OgvHJGF7yOpcxsbhMFEMVNgVUvk
Content-Type: application/json

{
  "type": "text",
  "isPublished": true,
  "titleText": "Расширенный текст публикации"
}
###

# Delete post
DELETE http://localhost:3000/api/blog/6a17820e-9181-47e7-ae49-4d91b084f410 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzcxMjE0NCwiZXhwIjoxNzM3NzEyNDQ0fQ.Rz0YqEKh0lXDTkIxMvY7JUqA4CgBXO4BY2Ynj5GotTc
Content-Type: application/json

###