# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiI5ZmMzODUxYy1lNDMwLTQwZjQtODQxNi0xNDJkODhlZTYzZWYiLCJpYXQiOjE3Mzc1MzYzODEsImV4cCI6MTc0MDEyODM4MX0.h5qVjYKF_76SPRFhRULzOQ6E2_KXgkZd7AWVLWnQeH8

###

# Create a new post
POST http://localhost:3000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzc0MDAxNiwiZXhwIjoxNzM3NzQwMzE2fQ.2-uvPeQp05abW0l_Xyb4AJZRKvFz9G-ZcPYPQLhgPQo
Content-Type: application/json

{
  "type": "link",
  "urlLink": "https://up.htmlacademy.ru/profession/fullstack/8/nodejs-2/8/project/readme"
}
###

# Delete post
DELETE http://localhost:3000/api/blog/6a17820e-9181-47e7-ae49-4d91b084f4101 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzc3NjgxNCwiZXhwIjoxNzM3Nzc3MTE0fQ.764_ksZUkf5nz9bKwqXvTRXlqL7Fy6xSYZ5B1Wb_H3I
Content-Type: application/json

###
# Get post
GET http://localhost:3000/api/blog/1e3cb76b-8ec4-4d23-b930-c186d6fb2d1c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzc0MTcyOSwiZXhwIjoxNzM3NzQyMDI5fQ.l7GVE415OOQOUBqE-UxwOrX5KhrA8WuDo26MTfcvX8c
Content-Type: application/json

###
# Update post
PATCH http://localhost:3000/api/blog/1e3cb76b-8ec4-4d23-b930-c186d6fb2d1c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY2ZTE2ZjkwYzAyNjRhNzRhMWY5ZDQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzc3NzE1MiwiZXhwIjoxNzM3Nzc3NDUyfQ.7HAJFDIzUHkaYT8vIpOpHejVSUqA-df_XWNC8bLxSKU
Content-Type: application/json

{
  "tags": ["tag1", "tag2"],
  "postDate": "2025-01-30T17:37:50.831Z",
  "isPublished": false,
  "likes": [],
  "comments": [],
  "urlLink": "https://up.htmlacademy.ru/profession/fullstack/8/nodejs-2/8/project/readme"
}
###