# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "name": "Keks",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/676563fd26fb301fc2b91b89 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzM2NTAzMCwiZXhwIjoxNzM3MzY1MzMwfQ.OcaNciCiSwnFNI_aKKoaVoA3X12OsZ9v3MHKyCjvQ8s